replicaCount: 1

image:
  repository: ghcr.io/BesQpin/open-kube-event-exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

loki:
  enabled: true
  url: ""
  tenantID: ""
