name: Release

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  APP_NAME: open-kube-event-exporter


jobs:

  set-vars:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ needs.set-vars.outputs.app_name }}
    steps:
      - run: echo "APP_NAME=${{ needs.set-vars.outputs.app_name }}"

  build:
    name: Build binaries
    runs-on: ubuntu-latest
    needs: set-vars

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: |
          go mod tidy -x -v
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ needs.set-vars.outputs.app_name }}-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-vars.outputs.app_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  publish-docker-image:
    uses: besqpin/workflow-library/.github/workflows/ghcr-publish-image.yaml@main
    needs: [build, set-vars]
    with:
      APP_NAME: ${{ needs.set-vars.outputs.app_name }}
      image-path: .
      ghcr-org: besqpin
      image-name: open-kube-event-exporter
      event_name: ${{ github.event_name }}
      pr_merged: ${{ github.event.pull_request && github.event.pull_request.merged || false }}
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  publish-helm-chart:
      uses: besqpin/workflow-library/.github/workflows/ghcr-publish-helm.yaml@main
      needs: publish-docker-image
      with:
        chart-path: charts
        ghcr-org: besqpin
        chart-name: open-kube-event-exporter
        event_name: ${{ github.event_name }}
        pr_merged: ${{ github.event.pull_request && github.event.pull_request.merged || false }}
      secrets:
        GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}