name: Release Open Kube Event Exporter

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  APP_NAME: open-kube-event-exporter
  GO_VERSION: "1.24"

jobs:
  # --------------------------------
  # 1️⃣ Set variables from env
  # --------------------------------
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.export.outputs.app_name }}
      go_version: ${{ steps.export.outputs.go_version }}
    steps:
      - id: export
        run: | 
          echo "app_name=${{ env.APP_NAME }}" >> $GITHUB_OUTPUT
          echo "go_version=${{ env.GO_VERSION }}" >> $GITHUB_OUTPUT


  # --------------------------------
  # 2️⃣ Version resolution or bump
  # --------------------------------
  versioning:
    uses: besqpin/workflow-library/.github/workflows/versioning.yaml@main
    with:
      event_name: ${{ github.event_name }}
      pr_merged: ${{ github.event.pull_request && github.event.pull_request.merged || false }}
      mode: ${{ github.ref_type == 'tag' && 'read' || 'bump' }}

  # --------------------------------
  # 3️⃣ Build Go binaries (reusable workflow)
  # --------------------------------
  build-go:
    uses: besqpin/workflow-library/.github/workflows/go-build.yaml@main
    needs: [set-vars, versioning]
    with:
      go-version: ${{ needs.set-vars.outputs.go_version }}
      app-name: ${{ needs.set-vars.outputs.app_name }}
      version: ${{ needs.versioning.outputs.version }}

  # --------------------------------
  # 4️⃣ Build & push Docker image
  # --------------------------------
  publish-docker-image:
    uses: besqpin/workflow-library/.github/workflows/ghcr-publish-image.yaml@main
    needs: [build-go, set-vars, versioning]
    with:
      APP_NAME: ${{ needs.set-vars.outputs.app_name }}
      version: ${{ needs.versioning.outputs.version }}
      image-path: .
      ghcr-org: besqpin
      image-name: ${{ needs.set-vars.outputs.app_name }}
      event_name: ${{ github.event_name }}
      pr_merged: ${{ github.event.pull_request && github.event.pull_request.merged || false }}
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  # --------------------------------
  # 5️⃣ Publish Helm chart
  # --------------------------------
  publish-helm-chart:
    uses: besqpin/workflow-library/.github/workflows/ghcr-publish-helm.yaml@main
    needs: [build-go, set-vars, publish-docker-image, versioning]
    with:
      chart-path: charts
      ghcr-org: besqpin
      chart-name: ${{ needs.set-vars.outputs.app_name }}
      version: ${{ needs.versioning.outputs.version }}
      event_name: ${{ github.event_name }}
      pr_merged: ${{ github.event.pull_request && github.event.pull_request.merged || false }}
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  # --------------------------------
  # 6️⃣ Tag & Release
  # --------------------------------
  release:
    needs: [build-go, set-vars, publish-docker-image, versioning, publish-helm-chart]
    uses: besqpin/workflow-library/.github/workflows/tag-and-release.yaml@main
    with:
      image: ${{ needs.publish-docker-image.outputs.image }}
      version: ${{ needs.versioning.outputs.version }}
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
