name: Release

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

env:
  APP_NAME: open-kube-event-exporter


jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: |
          go mod tidy -x -v
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    docker:
      uses: besqpin/workflow-library/.github/workflows/ghcr-publish-image.yaml@main
      with:
        image-path: base-chart
        ghcr-org: besqpin
        image-name: open-kube-event-exporter
        event_name: ${{ github.event_name }}
        pr_merged: ${{ github.event.pull_request && github.event.pull_request.merged || false }}
      secrets:
        GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    
    helm:
      ghcr-publish:
        uses: besqpin/workflow-library/.github/workflows/ghcr-publish-helm.yaml@main
        with:
          chart-path: charts
          ghcr-org: besqpin
          chart-name: open-kube-event-exporter
          event_name: ${{ github.event_name }}
          pr_merged: ${{ github.event.pull_request && github.event.pull_request.merged || false }}
        secrets:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}